# Site settings
title: LTEC 647C Blog
header-img: img/pattern.png
email: -
description: ""
baseurl: "/weblog"
url: "http://yourdomain.com"
twitter_username: 
github_username:  chelleis
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
