# Site settings
title: LTEC 647C Blog
header-img: img/pattern.png
email: email@yourdomain.com
description: ""
baseurl: "/weblog"
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
